-- GAD-7 finalized assessment outcomes
-- Run this in Supabase SQL editor.

create table if not exists public.gad7_assessments (
  id bigint generated by default as identity primary key,
  user_id text not null,
  conversation_id text not null default 'default',
  status text not null check (status in ('completed', 'crisis_terminated')),
  q1_score integer,
  q2_score integer,
  q3_score integer,
  q4_score integer,
  q5_score integer,
  q6_score integer,
  q7_score integer,
  total_score integer,
  anxiety_level text,
  assessed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_gad7_assessments_user_id
  on public.gad7_assessments (user_id);

create index if not exists idx_gad7_assessments_assessed_at
  on public.gad7_assessments (assessed_at desc);

-- Optional integrity checks:
-- completed rows should have full scores + total + level
alter table public.gad7_assessments
  drop constraint if exists gad7_assessments_completed_has_scores;

alter table public.gad7_assessments
  add constraint gad7_assessments_completed_has_scores check (
    status <> 'completed'
    or (
      q1_score is not null and q2_score is not null and q3_score is not null and
      q4_score is not null and q5_score is not null and q6_score is not null and q7_score is not null and
      total_score is not null and anxiety_level is not null
    )
  );

-- crisis_terminated rows should keep score fields empty
alter table public.gad7_assessments
  drop constraint if exists gad7_assessments_crisis_empty_scores;

alter table public.gad7_assessments
  add constraint gad7_assessments_crisis_empty_scores check (
    status <> 'crisis_terminated'
    or (
      q1_score is null and q2_score is null and q3_score is null and
      q4_score is null and q5_score is null and q6_score is null and q7_score is null and
      total_score is null and anxiety_level is null
    )
  );

-- Enforce 0-3 per-question scale and valid GAD-7 total range.
alter table public.gad7_assessments
  drop constraint if exists gad7_assessments_score_ranges;

alter table public.gad7_assessments
  add constraint gad7_assessments_score_ranges check (
    status <> 'completed'
    or (
      q1_score between 0 and 3 and
      q2_score between 0 and 3 and
      q3_score between 0 and 3 and
      q4_score between 0 and 3 and
      q5_score between 0 and 3 and
      q6_score between 0 and 3 and
      q7_score between 0 and 3 and
      total_score between 0 and 21
    )
  );

alter table public.gad7_assessments
  drop constraint if exists gad7_assessments_level_values;

alter table public.gad7_assessments
  add constraint gad7_assessments_level_values check (
    anxiety_level is null
    or anxiety_level in ('minimal', 'mild', 'moderate', 'severe')
  );
