-- PHQ-9 finalized assessment outcomes
-- Run this in Supabase SQL editor.

create table if not exists public.phq9_assessments (
  id bigint generated by default as identity primary key,
  user_id text not null,
  conversation_id text not null default 'default',
  status text not null check (status in ('completed', 'crisis_terminated')),
  q1_score integer,
  q2_score integer,
  q3_score integer,
  q4_score integer,
  q5_score integer,
  q6_score integer,
  q7_score integer,
  q8_score integer,
  q9_score integer,
  total_score integer,
  depression_level text,
  assessed_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists idx_phq9_assessments_user_id
  on public.phq9_assessments (user_id);

create index if not exists idx_phq9_assessments_assessed_at
  on public.phq9_assessments (assessed_at desc);

alter table public.phq9_assessments
  drop constraint if exists phq9_assessments_completed_has_scores;

alter table public.phq9_assessments
  add constraint phq9_assessments_completed_has_scores check (
    status <> 'completed'
    or (
      q1_score is not null and q2_score is not null and q3_score is not null and
      q4_score is not null and q5_score is not null and q6_score is not null and
      q7_score is not null and q8_score is not null and q9_score is not null and
      total_score is not null and depression_level is not null
    )
  );

alter table public.phq9_assessments
  drop constraint if exists phq9_assessments_crisis_empty_scores;

alter table public.phq9_assessments
  add constraint phq9_assessments_crisis_empty_scores check (
    status <> 'crisis_terminated'
    or (
      q1_score is null and q2_score is null and q3_score is null and
      q4_score is null and q5_score is null and q6_score is null and
      q7_score is null and q8_score is null and q9_score is null and
      total_score is null and depression_level is null
    )
  );
